name: Deploy to Server

on:
  push:
    branches:
    - public
    - master

env:
  NODE_VERSION: '12.16.1'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        npm install
        npm run build --if-present
        npm run test --if-present
    - name: 'Deploy to Server'
      uses: BuildPC/rsync-with-ssh-github-actions@master
      env:
        HELLO: cool
        MESSAGE: hello world
      with:
        key: ${{ secrets.SERVER_SSH_KEY }}
        host: ${{ secrets.SERVER_IP }}
        port: ${{ secrets.SERVER_PORT }}
        user: ${{ secrets.USERNAME }}
        destination: ${{ secrets.SERVER_DESTINATION }}
        # runs this on remove server
        ssh_before: |
          echo $HELLO
          echo $MESSAGE
          ls -lath

        # then run these commands
        ssh_after: |
          echo $HELLO
          echo $MESSAGE
          ls -lath
       

